package com.games.gamex.utils

enum class Shimmer {
    GAME_ITEM_HORIZONTAL_PLACEHOLDER,
    CATEGORIES_ITEM_PLACEHOLDER,
    PLATFORM_ITEM_PLACEHOLDER,
    GAME_ITEM_VERTICAL_PLACEHOLDER,
    GAME_DETAIL_PLACEHOLDER
}